server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.25.98.127:3306/enote_dev?characterEncoding=utf8
    username: root
    password:
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  #配置MVC视图解析
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
  #配置redis
  redis:
    database: 0
    host: 118.25.98.127
    port: 6379
    password:
    pool:
      max-active: 8
    #最大阻塞等待时间（负值表示没有限制）
      max-wait: 1
    #最大空闲链接
      max-idle: 8
    # 最小空闲链接
      min-idle: 0
    #链接超时时间（毫秒）
    timeout: 0
#  #Dao使用JPA方式
#  jpa:
#    database: mysql
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
mybatis:
  #实体类所在包别名
  type-aliases-package: com.grand.enoteboot.entity
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml
  #下划线转驼峰
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.grand.enoteboot.dao: debug
